# Generated by Django 5.2.17 on 2026-10-05 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('type', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('success', 'Succès'), ('error', 'Erreur'), ('low_stock', 'Stock faible'), ('repair_ready', 'Réparation prête'), ('repair_assigned', 'Réparation assignée'), ('repair_waiting', 'En attente client'), ('payment_pending', 'Paiement en attente')], default='info', max_length=20, verbose_name='type')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='reference type')),
                ('reference_id', models.UUIDField(blank=True, null=True, verbose_name='reference ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'is_read'], name='notificatio_employe_a487d8_idx'), models.Index(fields=['employee', 'created_at'], name='notificatio_employe_2c9482_idx'), models.Index(fields=['type'], name='notificatio_type_ea918f_idx')],
            },
        ),
    ]
