export { api } from './axios'
export * from './auth.api'
export * from './dashboard.api'
export * from './customers.api'
export * from './devices.api'
export * from './repairs.api'
export * from './products.api'
export * from './sales.api'
export * from './payments.api'
export * from './invoices.api'
export * from './employees.api'
export * from './content.api'
export * from './robotics.api'
