# Generated by Django 5.2.17 on 2026-10-05 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('status_change', 'Changement de statut'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('confirm', 'Confirmation'), ('cancel', 'Annulation'), ('payment', 'Paiement'), ('invoice', 'Facturation'), ('inventory_adjustment', 'Ajustement stock'), ('export', 'Export')], max_length=30, verbose_name='action')),
                ('entity_type', models.CharField(max_length=50, verbose_name='entity type')),
                ('entity_id', models.UUIDField(blank=True, null=True, verbose_name='entity ID')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='old data')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='new data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'created_at'], name='audit_audit_employe_8ff9eb_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx')],
            },
        ),
    ]
