# Generated by Django 5.2.17 on 2026-10-05 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='company name')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('governorate', models.CharField(blank=True, choices=[('ariana', 'Ariana'), ('beja', 'Béja'), ('ben_arous', 'Ben Arous'), ('bizerte', 'Bizerte'), ('gabes', 'Gabès'), ('gafsa', 'Gafsa'), ('jendouba', 'Jendouba'), ('kairouan', 'Kairouan'), ('kasserine', 'Kasserine'), ('kebili', 'Kébili'), ('kef', 'Le Kef'), ('mahdia', 'Mahdia'), ('manouba', 'Manouba'), ('medenine', 'Medenine'), ('monastir', 'Monastir'), ('nabeul', 'Nabeul'), ('sfax', 'Sfax'), ('sidi_bouzid', 'Sidi Bouzid'), ('siliana', 'Siliana'), ('sousse', 'Sousse'), ('tataouine', 'Tataouine'), ('tozeur', 'Tozeur'), ('tunis', 'Tunis'), ('zaghouan', 'Zaghouan')], max_length=20, verbose_name='governorate')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'), models.Index(fields=['last_name', 'first_name'], name='customers_c_last_na_27dbcc_idx'), models.Index(fields=['is_active'], name='customers_c_is_acti_91d305_idx'), models.Index(fields=['governorate'], name='customers_c_governo_61f9da_idx')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('printer', 'Printer'), ('server', 'Server'), ('phone', 'Phone'), ('other', 'Other')], max_length=20, verbose_name='device type')),
                ('brand', models.CharField(max_length=100, verbose_name='brand')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='serial number')),
                ('device_password', models.CharField(blank=True, max_length=200, verbose_name='device password')),
                ('accessories', models.TextField(blank=True, verbose_name='accessories')),
                ('physical_condition', models.TextField(blank=True, verbose_name='physical condition')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='customers.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'device_type'], name='customers_d_custome_dfb67a_idx'), models.Index(fields=['serial_number'], name='customers_d_serial__008778_idx'), models.Index(fields=['brand', 'model'], name='customers_d_brand_5a8bb5_idx')],
            },
        ),
    ]
