# Generated by Django 5.2.17 on 2026-10-05 21:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('repairs', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='invoice number')),
                ('subtotal', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='subtotal')),
                ('discount', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='discount')),
                ('tax', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='tax')),
                ('total', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='total')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='issued at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer', verbose_name='customer')),
                ('repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='repairs.repairticket', verbose_name='repair')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.sale', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['invoice_number'], name='invoices_in_invoice_e6b546_idx'), models.Index(fields=['customer', 'issued_at'], name='invoices_in_custome_cb7fdc_idx'), models.Index(fields=['sale'], name='invoices_in_sale_id_77e694_idx'), models.Index(fields=['repair'], name='invoices_in_repair__319658_idx')],
            },
        ),
    ]
